#!/usr/bin/env bash
LC_ALL=C

local_branch="$(git rev-parse --abbrev-ref HEAD)"

valid_branch_regex="^((feature|bugfix|improvement|release|hotfix|rewrite)\/[a-z0-9._-]+)|(main)|(dev)$"

message="Your commit was rejected because your branch does not have a valid name.
Branch names in this project should comply with the following regular expression: $valid_branch_regex."

if [[ ! $local_branch =~ $valid_branch_regex ]]
then
    echo "$message"
    exit 1
fi

exit 0
