dirs:
  local: False
  localDir: "/home/llr/cms/ehle/NewRepos/bye_splits/data/new_algos/"
  ehleDir: "/eos/user/i/iehle/"
  dataFolder: "data/"

clusterSize:
  pileUp: False
  tree: "FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple/HGCalTriggerNtuple"
  coeffs: [0.0, 0.05, 50]
  #fileBaseName: "cluster_size"
  fileBaseName: "energy_out"
