defaultEvents:
    photons: [170032, 170044]
    electrons: [92243, 92244]
    pions: [5613]

geometry:
    waferSize: 16.64408
    sensorSeparation: 0.1
    nlayersCEE: 28

varEvents:
  gen:
    event: 'event'
    geta: 'good_genpart_exeta'
    gphi: 'good_genpart_exphi'
    gen: 'good_genpart_energy'
  tc:
    event: 'event'
    wu: 'good_tc_waferu'
    wv: 'good_tc_waferv'
    l:  'good_tc_layer'
    cv: 'good_tc_cellu'
    cu: 'good_tc_cellv'
    x: 'good_tc_x'
    y: 'good_tc_y'
    z: 'good_tc_z'
    phi: 'good_tc_phi'
    eta: 'good_tc_eta'
    idcl: 'good_tc_cluster_id'
    pt: 'good_tc_pt'
    en: 'good_tc_mipPt'
  # tsum:
  #   event: 'event'
  #   wu: 'good_ts_waferu'
  #   wv: 'good_ts_waferv'
  #   l:  'good_ts_layer'
  #   en: 'good_ts_mipPt'
  cl:
    event: 'event'
    eta: 'good_cl3d_eta'
    phi: 'good_cl3d_phi'
    en: 'good_cl3d_energy'
    id: 'good_cl3d_id'
    # matches: 'matches'
    # dR: 'deltaR'
    
varGeometry:
    wu: 'waferu'
    wv: 'waferv'
    l: 'layer'
    cu: 'triggercellu'
    cv: 'triggercellv'
    ieta: 'triggercellieta'
    iphi: 'triggercelliphi'
    x: 'x'
    y: 'y'
    z: 'z'
    side: 'zside'
    subd: 'subdet'
    wvs: 'waferv_shift'
    c: 'color'
    orient: 'waferorient'
    part: 'waferpart'
