defaultEvents:
    photons: [4681, 4677]
    electrons: [92013, 92027]
    pions: [5538, 5724]

geometry:
    waferSize: 16.64408
    sensorSeparation: 0.1

varEvents:
  gen:
    event: 'event'
  tc:
    event: 'event'
    wu: 'good_tc_waferu'
    wv: 'good_tc_waferv'
    l:  'good_tc_layer'
    cv: 'good_tc_cellu'
    cu: 'good_tc_cellv'
    en: 'good_tc_mipPt'
  # tsum:
  #   event: 'event'
  #   wu: 'good_ts_waferu'
  #   wv: 'good_ts_waferv'
  #   l:  'good_ts_layer'
  #   en: 'good_ts_mipPt'
  cl:
    event: 'event'

varGeometry:
    wu: 'waferu'
    wv: 'waferv'
    l: 'layer'
    cu: 'triggercellu'
    cv: 'triggercellv'
    x: 'x'
    y: 'y'
    z: 'z'
    side: 'zside'
    subd: 'subdet'
    wvs: 'waferv_shift'
    c: 'color'
    orient: 'waferorient'
    part: 'waferpart'

###[170017, 170010]
