io:
    dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
    tree: HGCalTriggerNtuple

selection:
    disconnectedTriggerLayers: [2,4,6,8,10,12,14,16,18,20,22,24,26,28]
    reachedEE: 2
    deltarThreshold: 0.05
    mipThreshold: 0.5

###    dir: hgcalTriggerNtuplizer
###    tree: HGCalTriggerNtuple
