io:
  dir: FloatingpointMixedbcstcrealsig4DummyHistomaxxydr015GenmatchGenclustersntuple
  tree: HGCalTriggerNtuple
  photons: /eos/user/i/iehle/data/PU0/photons/skim_photons_0PU_bc_stc_hadd.root
  electrons: /eos/user/i/iehle/data/PU0/electrons/skim_electrons_0PU_bc_stc_hadd.root
  pions: /eos/user/i/iehle/data/PU0/pions/skim_pions_0PU_bc_stc_hadd.root

geom:
    dir: L1THGCaltriggergeomtester
    tree: TreeTriggerCells
    file: /data_CMS/cms/alves/L1HGCAL/test_triggergeom_12_5_2_patch1_FIXED_v2.root

selection:
    particles: photons
    disconnectedTriggerLayers: [2,4,6,8,10,12,14,16,18,20,22,24,26,28]
    reachedEE: 2
    deltarThreshold: 0.05
    mipThreshold: 0.5

clSize:
  reinit: False
  clusterSizeBaseName: cluster_size
  coeffs: [0.0, 0.05, 50]
  nevents: 100
